# Generated by Django 2.2.12 on 2022-04-27 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Lösungstext')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kursname')),
                ('semester', models.CharField(max_length=10, verbose_name='Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Aufgabentext')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=50, verbose_name='Nachname')),
                ('surname', models.CharField(max_length=50, verbose_name='Vorname')),
            ],
        ),
        migrations.CreateModel(
            name='ExercisePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Pfad')),
                ('text', models.TextField(verbose_name='Bildbeschreibung')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='exgen.Exercise', verbose_name='Aufgabe')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy', models.CharField(choices=[('even', 'Gleichgestellt'), ('higher', 'Höhergestellt')], max_length=10, verbose_name='Hierarchie')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='exgen.Exercise')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='exgen.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excercise_categories', to='exgen.Category', verbose_name='Kategorie')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exgen.Exercise', verbose_name='Aufgabe')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.ManyToManyField(through='exgen.ExerciseCategory', to='exgen.Category', verbose_name='Kategorien'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='exgen.Lecturer', verbose_name='Ersteller'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='dependency',
            field=models.ManyToManyField(blank=True, through='exgen.ExerciseDependency', to='exgen.Exercise', verbose_name='Abhängig von'),
        ),
        migrations.CreateModel(
            name='CourseExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_courses', to='exgen.Course', verbose_name='Kurs')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_exercises', to='exgen.Exercise', verbose_name='Aufgabe')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_categories', to='exgen.Category', verbose_name='Kategorie')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_courses', to='exgen.Course', verbose_name='Kurs')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(through='exgen.CourseCategory', to='exgen.Category', verbose_name='Kategorien'),
        ),
        migrations.AddField(
            model_name='course',
            name='exercise',
            field=models.ManyToManyField(blank=True, through='exgen.CourseExercise', to='exgen.Exercise', verbose_name='Benutzte Aufgaben'),
        ),
        migrations.CreateModel(
            name='AnswerPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='Pfad')),
                ('text', models.TextField(verbose_name='Bildbeschreibung')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='exgen.Answer', verbose_name='Lösung')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exgen.Exercise', verbose_name='Lösung'),
        ),
    ]
