# Generated by Django 4.0.5 on 2022-06-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exgen', '0001_squashed_0009_alter_assembly_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
