# Generated by Django 2.2.12 on 2022-05-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exgen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpicture',
            name='location',
        ),
        migrations.RemoveField(
            model_name='exercisepicture',
            name='location',
        ),
        migrations.AddField(
            model_name='answerpicture',
            name='image',
            field=models.ImageField(default='abc', max_length='200', upload_to='answer_images/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisepicture',
            name='image',
            field=models.ImageField(default='abc', max_length='200', upload_to='exercise_images/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
