# Generated by Django 2.2.12 on 2022-05-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exgen', '0002_auto_20220528_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpicture',
            name='image',
            field=models.ImageField(max_length=200, upload_to='answer_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='exercisepicture',
            name='image',
            field=models.ImageField(max_length=200, upload_to='exercise_images/', verbose_name='Image'),
        ),
    ]
