# Generated by Django 4.0.5 on 2022-07-03 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exgen', '0002_alter_answer_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblycategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_categories', to='exgen.category', verbose_name='Categorie'),
        ),
    ]
