# Generated by Django 2.2.12 on 2022-06-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exgen', '0003_auto_20220528_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='text_type',
            field=models.CharField(choices=[('MARKDOWN', 'Markdown'), ('LATEX', 'Latex'), ('PLAIN', 'Plain')], default='MARKDOWN', max_length=15, verbose_name='Texttype'),
        ),
    ]
