# Generated by Django 4.0.5 on 2022-07-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exgen', '0003_alter_assemblycategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assemblycategory',
            old_name='Assembly',
            new_name='assembly',
        ),
    ]
