# Generated by Django 4.0.5 on 2022-07-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exgen', '0005_alter_exercise_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='exercise',
            managers=[
            ],
        ),
    ]
