# Generated by Django 4.0.5 on 2022-06-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exgen', '0005_alter_course_lecturer_alter_exercise_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerpicture',
            old_name='exercise',
            new_name='answer',
        ),
    ]
