# Generated by Django 4.0.5 on 2022-06-08 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exgen', '0006_rename_exercise_answerpicture_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('published', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_type',
            field=models.CharField(choices=[('MARKDOWN', 'Markdown'), ('LATEX', 'Latex'), ('PLAIN', 'Plain')], default='MARKDOWN', max_length=15, verbose_name='Texttype'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='ExerciseAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='Ordering number')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_assemblies', to='exgen.assembly', verbose_name='Assembly')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_exercises', to='exgen.exercise', verbose_name='Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assemblies', to='exgen.assembly', verbose_name='Assembly')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cassembly_categories', to='exgen.category', verbose_name='Categorie')),
            ],
        ),
        migrations.AddField(
            model_name='assembly',
            name='category',
            field=models.ManyToManyField(through='exgen.AssemblyCategory', to='exgen.category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='exgen.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assemblys', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='exercise',
            field=models.ManyToManyField(through='exgen.ExerciseAssembly', to='exgen.exercise', verbose_name='Exercises'),
        ),
    ]
