# Generated by Django 4.0.5 on 2022-06-08 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exgen', '0007_assembly_answer_date_created_answer_date_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='assembly',
            field=models.ManyToManyField(through='exgen.AssemblyCourses', to='exgen.assembly', verbose_name='Assemblies'),
        ),
        migrations.AddField(
            model_name='assemblycourses',
            name='assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assemblies', to='exgen.assembly', verbose_name='Assembly'),
        ),
        migrations.AddField(
            model_name='assemblycourses',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_courses', to='exgen.course', verbose_name='Course'),
        ),
    ]
