# Generated by Django 4.0.5 on 2022-06-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exgen', '0008_assemblycourses_remove_assembly_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
