---
- name: add deadsnakes repository
  shell: sudo add-apt-repository ppa:deadsnakes/ppa -y
  become_user: "{{ansible_user}}"
  changed_when: true

- name: install python3.10
  shell: sudo apt install python3.10 -y
  become_user: "{{ansible_user}}"
  changed_when: true

- name: install python3.10-distutils
  shell: sudo apt install python3.10-distutils -y
  become_user: "{{ansible_user}}"
  changed_when: true

- name: install pip3.10
  shell: sudo apt install python3-pip -y
  become_user: "{{ansible_user}}"
  changed_when: true
  
- name: install pip3.10 locally via download (fixes some issues for the global install)
  shell: curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
  become_user: "{{ansible_user}}"
  changed_when: true
